version: "3.8"

services:
  app:
    build: .
    container_name: pagamento-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network
      -
networks:
  app-network:
    driver: bridge
