# -------------------
# AWS Credentials
# -------------------
cloud.aws.region.static=${AWS_REGION:us-east-1}
notificacao.config.email=${NOTIFICACAO_EMAIL}
notificacao.config.senha=${NOTIFICACAO_SENHA}
server.port=8080