# -------------------
# AWS Credentials
# -------------------
cloud.aws.region.static=${AWS_REGION:us-east-1}
notificacao.config.email=<insira o email que vai enviar as notificações>
notificacao.config.senha=<insira a senha de app do email>
server.port=8080