spring.application.name=notificacao-app
spring.main.allow-bean-definition-overriding=true
spring.profiles.active=${SPRING_PROFILES_ACTIVE:develop}

# -------------------
# Swagger
# -------------------
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# -------------------
# Services
# -------------------
services.pedido.url=${SERVICE_PEDIDO:localhost:8081}
services.producao.url=${SERVICE_PRODUCAO:localhost:8083}

# -------------------
# Health
# -------------------
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true


# -------------------
# Mensageria
# -------------------
events.queues.sqs-notificar-falha=sqs-notificar-falha
notificacao.config.email=${NOTIFICACAO_EMAIL}
notificacao.config.senha=${NOTIFICACAO_SENHA}
