apiVersion: v1
kind: ConfigMap
metadata:
  name: notificacao-config
data:
  spring.profiles.active: ${SPRING_ACTIVE_PROFILE}
  services.pedido.url: ${SERVICE_PEDIDO}
  services.producao.url: ${SERVICE_PRODUCAO}